# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44514b2be599119d0dd87d0a632a71d3bfd8f63c9b4c46cf965b99ee15602e337f733855c92c6c8b7b8c16d51372bf7246b879122721eb3e499e5a4acf1fb40d

test:
  secret_key_base: dc3793388585fb3527cbcd7adb4bdb67c927442d91a2c3428ceb2aae55a70a0e67bed59204599b857fe83cd8e67b0ce191fda2ebaa56d53004bb855dbc79ca49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
